export const FETCH_TOP_STORIES_REQUESTED = 'FETCH_TOP_STORIES_REQUESTED';
export const FETCH_HN_SUCCESS = 'FETCH_HN_SUCCESS';
export const FETCH_HN_FAILED = 'FETCH_HN_FAILED';
export const FETCH_STORY_REQUESTED = 'FETCH_STORY_REQUESTED';
